package org.springframework.samples.petclinic.customers;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration test to verify PostgreSQL profile functionality.
 * This test validates that the application runs correctly with PostgreSQL
 * and that all entries described in V1__Create_customers_schema_postgresql.sql exist in the database.
 */
@SpringBootTest
@ActiveProfiles("postgres")
public class PostgreSqlIntegrationTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Test
    public void verifyTypesTableStructure() {
        // Check that types table id column is defined as INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL
        String columnQuery = """
            SELECT table_schema, column_name, data_type, is_nullable, is_identity, identity_generation
            FROM information_schema.columns
            WHERE table_name = 'types' AND column_name = 'id'
            """;

        List<Map<String, Object>> columnInfo = jdbcTemplate.queryForList(columnQuery);
        assertThat(columnInfo).hasSize(1);

        Map<String, Object> idColumn = columnInfo.get(0);
        assertThat(idColumn.get("column_name")).isEqualTo("id");
        assertThat(idColumn.get("data_type")).isEqualTo("integer");
        assertThat(idColumn.get("is_nullable")).isEqualTo("NO");
        // Check for identity column with GENERATED BY DEFAULT
        assertThat(idColumn.get("is_identity")).isEqualTo("YES");
        assertThat(idColumn.get("identity_generation")).isEqualTo("BY DEFAULT");

        // Check that pk_types constraint exists
        String constraintQuery = """
            SELECT constraint_name, table_name, constraint_type
            FROM information_schema.table_constraints
            WHERE table_name = 'types' AND constraint_name = 'pk_types'
            """;

        List<Map<String, Object>> constraintInfo = jdbcTemplate.queryForList(constraintQuery);
        assertThat(constraintInfo).hasSize(1);

        Map<String, Object> pkConstraint = constraintInfo.get(0);
        assertThat(pkConstraint.get("constraint_name")).isEqualTo("pk_types");
        assertThat(pkConstraint.get("table_name")).isEqualTo("types");
        assertThat(pkConstraint.get("constraint_type")).isEqualTo("PRIMARY KEY");

        // Check that idx_types_name index exists on types(name)
        String indexQuery = """
            SELECT schemaname, tablename, indexname, indexdef
            FROM pg_indexes
            WHERE tablename = 'types' AND indexname = 'idx_types_name'
            """;

        List<Map<String, Object>> indexInfo = jdbcTemplate.queryForList(indexQuery);
        assertThat(indexInfo).hasSize(1);

        Map<String, Object> index = indexInfo.get(0);
        assertThat(index.get("indexname")).isEqualTo("idx_types_name");
        assertThat(index.get("tablename")).isEqualTo("types");
        String indexDef = (String) index.get("indexdef");
        assertThat(indexDef).isEqualTo("CREATE INDEX idx_types_name ON public.types USING btree (name)");
    }
}
