spring:
  profiles:
    active: "postgres"
  datasource:
    url: jdbc:postgresql://postgresql:5432/pc_visits
    username: pc_visit
    password:
      valueFrom:
        secretKeyRef:
          name: postgresql-pc-visit-password
  config:
    import: configserver:http://config-server.petclinic:8888/

bpl:
  heap:
    dump:
      path: /tmp/dump

