spring:
  application:
    name: vets-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cache:
    cache-names: vets
  profiles:
    active: production
  cloud:
    consul:
      enabled: false
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

---
spring:
  config:
    activate:
      on-profile: discovery
  cloud:
    consul:
      enabled: true



