-- PostgreSQL schema migration for visits service

CREATE TABLE visits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    pet_id INTEGER NOT NULL,
    visit_date DATE,
    description VARCHAR(8192),
    CONSTRAINT pk_visits PRIMARY KEY (id)
);

CREATE INDEX idx_visits_pet_id ON visits (pet_id);
