apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "config-server.fullname" . }}
  labels:
    {{- include "config-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "config-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "config-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "config-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.spring.profiles.active }}"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: {{ .Values.spring.cloud.config.server.git.uri }}
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME
              value: "{{ .Values.spring.cloud.config.server.git.username }}"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD
              value: "{{ .Values.spring.cloud.config.server.git.password }}"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULTLABEL
              value: "{{ .Values.spring.cloud.config.server.git.defaultLabel }}"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS
              value: "{{ .Values.spring.cloud.config.server.git.searchPaths }}"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_CONFIG
              value: "TRACE"
            - name: ENCRYPT_KEYSTORE_ALIAS
              value: {{ .Values.encrypt.keystore.alias }}
            - name: ENCRYPT_KEYSTORE_PASSWORD
              valueFrom:
                {{- toYaml .Values.encrypt.keystore.password.valueFrom | nindent 16 }}
            - name: ENCRYPT_KEYSTORE_LOCATION
              value: "/keystore/keystore.p12"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .Values.liveness.delay }}
            periodSeconds: {{ .Values.liveness.timeout }}
            failureThreshold: 10
            httpGet:
              path: {{ .Values.liveness.path }}
              port: http
          readinessProbe:
            initialDelaySeconds: {{ .Values.readiness.delay }}
            periodSeconds: {{ .Values.readiness.timeout }}
            failureThreshold: 10
            httpGet:
              path: {{ .Values.readiness.path }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: keystore
              mountPath: /workspace/keystore
              readOnly: true
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: keystore
          secret:
            secretName: {{ include "config-server.fullname" . }}-keystore
            items:
              - key: keystore.p12
                path: keystore.p12
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
