apiVersion: v1
kind: Secret
metadata:
  name: {{ include "config-server.fullname" . }}-keystore
  labels:
    {{- include "config-server.labels" . | nindent 4 }}
type: Opaque
data:
  keystore.p12: {{ .Files.Get .Values.keystore.filePath | b64enc }}
