spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: false
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server
    kubernetes:
      discovery:
        enabled: false
        namespaces:
          - default
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
        - name: Retry
          args:
            retries: 1
            statuses: SERVICE_UNAVAILABLE
            methods: POST
      routes:
        - id: vets-service
          uri: lb://vets-service
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        - id: genai-service
          uri: lb://genai-service
          predicates:
            - Path=/api/genai/**
          filters:
            - StripPrefix=2
            - CircuitBreaker=name=genaiCircuitBreaker,fallbackUri=/fallback
    consul:
      enabled: false
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

---
spring:
  config:
    activate:
      on-profile: cloudconfig
  cloud:
    config:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: consul
  cloud:
    consul:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: kubernetes
  cloud:
    kubernetes:
      discovery:
        enabled: true


