spring:
  application:
    name: visits-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}:${random.value}

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}:${random.value}
