apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-cm-application
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  application.yml: |
    logging:
      level:
        org:
          springframework:
            cloud:
              gateway: info
