apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.profiles }}"
            - name: SPRING_CLOUD_KUBERNETES_DISCOVERY_NAMESPACES_0
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_DEBUG_OPTS
              value: ""
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY_FILTER
              value: "TRACE"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_CLIENT
              value: "TRACE"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_KUBERNETES
              value: "TRACE"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY_FILTER_LOADBALANCER
              value: "TRACE"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY_FILTER_NOLOADBALANCERCLIENT
              value: "TRACE"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_LOADBALANCER
              value: "TRACE"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_DISCOVERY
              value: "TRACE"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_KUBERNETES_DISCOVERY
              value: "TRACE"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_KUBERNETES_CLIENT
              value: "TRACE"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_KUBERNETES_SERVICEDISCOVERY
              value: "TRACE"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY_FILTER_REACTIVELOADBALANCERCLIENT
              value: "TRACE"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY_FILTER_FACTORY
              value: "TRACE"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY_FILTER_WEIGHTEDRESPONSETIME
              value: "TRACE"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY_FILTER_ROUNDROBIN
              value: "TRACE"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: debug
              containerPort: 5005
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .Values.liveness.delay }}
            periodSeconds: {{ .Values.liveness.timeout }}
            failureThreshold: 10
            httpGet:
              path: {{ .Values.liveness.path }}
              port: http
          readinessProbe:
            initialDelaySeconds: {{ .Values.readiness.delay }}
            periodSeconds: {{ .Values.readiness.timeout }}
            failureThreshold: 10
            httpGet:
              path: {{ .Values.readiness.path }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
