nameOverride: vets-service

image:
  repository: spring-petclinic-vets-service

spring:
  datasource:
    url: jdbc:postgresql://postgresql/pc_vet
    username: pc_vet
    password:
      valueFrom:
        secretKeyRef:
          name: postgresql-pc-vet-password
          key: password
