nameOverride: visits-service

image:
  repository: spring-petclinic-visits-service

spring:
  datasource:
    url: jdbc:postgresql://postgresql/pc_visit
    username: pc_visit
    password:
      valueFrom:
        secretKeyRef:
          name: postgresql-pc-visit-password
          key: password
