nameOverride: customers-service

image:
  repository: spring-petclinic-customers-service

spring:
  datasource:
    url: jdbc:postgresql://postgresql/pc_customer
    username: pc_customer
    password:
      valueFrom:
        secretKeyRef:
          name: postgresql-pc-customer-password
          key: password
