server.port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitflic.ru/project/ikuchmin/spring-petclinic-microservices-config.git
          default-label: aidemo
          search-paths: /compose
    consul:
      enabled: false
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.uuid}
        prefer-ip-address: true

---
spring:
  config:
    activate:
      on-profile: discovery
  cloud:
    consul:
      enabled: true

