spring:
  application:
    name: admin-server
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: false
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server
    consul:
      enabled: false
      discovery:
        enabled: false
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

---
spring:
  config:
    activate:
      on-profile: cloudconfig
  cloud:
    config:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: discovery
  cloud:
    consul:
      enabled: true
