apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-pc-vet-password
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.dbs.pc_vet.password | b64enc }}
