apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-pc-visits-password
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.dbs.pc_visits.password | b64enc }}
