nameOverride: ""
fullnameOverride: ""
postgresql:
  enabled: true
  fullnameOverride: postgresql
  auth:
    enablePostgresUser: false

  primary:
    extendedConfiguration: |
      max_connections = 100
      shared_buffers = 1GB
      effective_cache_size = 3GB
      maintenance_work_mem = 256MB
      checkpoint_completion_target = 0.9
      wal_buffers = 16MB
      default_statistics_target = 100
      random_page_cost = 1.1
      effective_io_concurrency = 200
      work_mem = 5242kB
      huge_pages = off
      min_wal_size = 1GB
      max_wal_size = 4GB

    extraEnvVars:
      - name: PC_CUSTOMER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgresql-pc-customer-password
            key: password
      - name: PC_VET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgresql-pc-vet-password
            key: password
      - name: PC_VISIT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgresql-pc-visit-password
            key: password

    initdb:
      scripts:
        00_create_users.sh: |
          #!/bin/sh
          echo "Running creation users task"
          
          export PGPASSWORD=$POSTGRESQL_INITSCRIPTS_PASSWORD
          
          psql -c "CREATE USER pc_customer PASSWORD '${PC_CUSTOMER_PASSWORD}'"
          psql -c "CREATE USER pc_vet PASSWORD '${PC_VET_PASSWORD}'"
          psql -c "CREATE USER pc_visit PASSWORD '${PC_VISIT_PASSWORD}'"

        01_create_databases.sh: |
          #!/bin/sh
          echo "Running creation databases task"
          
          export PGPASSWORD=$POSTGRESQL_INITSCRIPTS_PASSWORD
          
          psql -c "CREATE DATABASE pc_customer OWNER pc_customer"
          psql -c "CREATE DATABASE pc_vet OWNER pc_vet"
          psql -c "CREATE DATABASE pc_visit OWNER pc_visit"

dbs:
  pc_visits:
    password: KSf8gtp3K1mYoMy
  pc_customers:
    password: SXj0254Cp9QbVGc
  pc_vets:
    password: NWh51Wc8YgzSC0c
