CREATE TABLE vet_specialties
(
    specialty_id INT NOT NULL,
    vet_id       INT NOT NULL,
    CONSTRAINT pk_vet_specialties PRIMARY KEY (specialty_id, vet_id)
);

CREATE TABLE specialties
(
    id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_specialties PRIMARY KEY (id)
);

CREATE TABLE vets
(
    id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    CONSTRAINT pk_vets PRIMARY KEY (id)
);

ALTER TABLE vet_specialties
    ADD CONSTRAINT fk_vetspe_on_specialty FOREIGN KEY (specialty_id) REFERENCES specialties (id);

ALTER TABLE vet_specialties
    ADD CONSTRAINT fk_vetspe_on_vet FOREIGN KEY (vet_id) REFERENCES vets (id);

-- Add indexes for better query performance
CREATE INDEX idx_vets_last_name ON vets (last_name);
CREATE INDEX idx_specialties_name ON specialties (name);
CREATE INDEX idx_vet_specialties_vet_id ON vet_specialties (vet_id);
CREATE INDEX idx_vet_specialties_specialty_id ON vet_specialties (specialty_id);
