profiles: git

image:
  tag: "3.4.1"

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitflic.ru/project/ikuchmin/spring-petclinic-microservices-config.git
          defaultLabel: aidemo
          searchPaths: /production

encrypt:
  keystore:
    alias: compose
    password:
      valueFrom:
        secretKeyRef:
          name: config-server-keystore-password
          key: password

keystore:
  filePath: keystore/keystore.p12
