{{- if or (eq .Values.spring.profiles.active "kubernetes") (regexMatch "^(.*,)?kubernetes(,.*)?$" .Values.spring.profiles.active) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vets-service.fullname" . }}-discovery
  labels:
    {{- include "vets-service.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vets-service.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "vets-service.fullname" . }}-discovery
  apiGroup: rbac.authorization.k8s.io
  {{- end }}
